Death Player
Zadir7/SpaceRogue pull request #28
Opened 2022-08-23 10:10 UTC by OlegBakulin

2022-08-29 04:16 UTC, Zadir7 requested changes
Нужно дорабатывать

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/Gameplay/GameController.cs
> +        public static void EditorStatusGameOnMenu()
Тоже не должен быть static

ExitToMenu

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/Gameplay/GameController.cs
> +        public void OnPlayerDestroyed()
private
Нафига он публичный, кому нужен к нему доступ?

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Abstracts/AbstractDestroyPlayerView.cs
> +public abstract class AbstractDestroyPlayerView : MonoBehaviour, IDestroyPlayerView
А нафига оно абстрактное?
Читай коммент к интерфейсу.

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Abstracts/DestroyPlayerButtonView.cs
> +}
Убирай.
Вообще не понял шо за фигня тут

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Abstracts/DestroyPlayerView.cs
> +    {
Тут должна быть ссылка на компонент Button.

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Abstracts/DestroyPlayerView.cs
> +{
Тут должен быть атрибут [RequireComponent(typeof(Button))]

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Abstracts/DestroyPlayerView.cs
> +
Тут должна заполняться ссылка на Button.
И добавление listener'a _button.AddListener(onClickAction)

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +            DestroyPlayerViewComponent.gameObject.GetComponentInChildren<Button>().onClick.AddListener(QuitGame);
Эта штука будет происходить в ButtonView.

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        }
Зачем пустой метод?
Заполни его, выставляй тут все статические поля в null.

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        public static DestroyPlayerView DestroyPlayerViewComponent { get; private set; }
Он тебе тут статический не нужен

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        }
Этого тут не должно быть

2022-08-29 04:16 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        }
Тоже уже не должно быть

2022-08-31 14:18 UTC, OlegBakulin commented on Assets/Scripts/Gameplay/Camera/CameraController.cs
> +            playerPosition = _playerView ? _playerView.gameObject.transform.position : playerPosition;
Сделал через Try catch так как это перемещение камеры за игроком и при смерти, в старом исполнении, вылезала ошибка так как позиция игрока становилась null

2022-08-31 14:28 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Camera/CameraController.cs
> +            catch { }
Еще хуже
1. try catch это тяжелая операция по определению
2. Пустой catch

Сделай так как было описано в прошлом комменте.

2022-08-31 14:30 UTC, Zadir7 commented on Assets/Scripts/Gameplay/GameController.cs
> +            _gameUIController.DestroyPlayerViewComponent.gameObject.GetComponentInChildren<Button>().onClick.AddListener(EditorStatusGameOnMenu);
Даже 3х уровневый доступ (Something.GetSomething().Result) считается плохой практикой, у тебя здесь ШЕСТЬ уровней через которые ты прыгаешь.

2022-08-31 14:33 UTC, Zadir7 requested changes

2022-08-31 14:33 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        }
Это все еще тут лишнее

2022-08-31 14:33 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        public DestroyPlayerView DestroyPlayerViewComponent { get; private set; }
Это тоже не нужно.

2022-08-31 14:36 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Camera/CameraController.cs
> +            playerPosition = _playerView ? _playerView.gameObject.transform.position : playerPosition;
Сделал еще хуже чем было, см. коммент.

2022-09-04 03:37 UTC, Zadir7 requested changes
Сцену на место вернул, молодец
В остальном ничего не изменилось, кроме того что ты зарезолвил мои комменты.

2022-09-04 03:37 UTC, Zadir7 commented on Assets/Scenes/MainScene.unity
> +  m_LocalPosition: {x: 1000, y: 1000, z: 0}
Все еще тут

2022-09-04 03:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Camera/CameraController.cs
>          }
А оно где-то вызывается или подписывается? Не увидел этот момент

2022-09-08 07:06 UTC, Zadir7 requested changes
В принципе осталось немного

2022-09-08 07:06 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        private Canvas _playerDestroyPlayerCanvas;
Переименуй
_playerDestroyedCanvas

2022-09-08 07:06 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        private DestroyPlayerMessageView _playerDestroyPlayerView;
Переименуй
PlayerDestroyedMessageView
_playerDestroyedMessageView

2022-09-08 07:06 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +        private readonly ResourcePath _playerDestroyPlayerCanvasPath = new("Prefabs/Canvas/Game/DestroyPlayerCanvas");
_playerDestroyedCanvasPath

2022-09-08 07:06 UTC, Zadir7 commented on Assets/Scripts/UI/Game/GameUIController.cs
> +            _playerDestroyPlayerView.DestroyPlayerButton.Init(_exitToMenu);
Сделай у _playerDestroyedMessageView тоже метод Init, и в нем прокинь Init кнопки, чтобы опять же не было трех-уровневого доступа

2022-09-12 12:37 UTC, merged