Added state for enemy
Zadir7/SpaceRogue pull request #30
Opened 2022-09-01 17:21 UTC by ivan1209-stack

2022-09-04 04:06 UTC, Zadir7 requested changes
В целом хорошо, поправить немного нейминг и ответить на вопросы

2022-09-04 04:06 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            var currentDirection = View.transform.InverseTransformDirection(Vector3.up);
А почему InverseTransformDirection?

2022-09-04 04:06 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            if (!UnityHelper.Approximately(_targetDirection, currentDirection, 0.1f))
Если НЕ смотрим на цель, стрелять?)

2022-09-04 04:06 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +        private void TurnToRandomDirection()
Почему TurnToRandomDirection если тут ты на игрока поворачиваешься?)
RotateTowardsPlayer

2022-09-04 04:06 UTC, Zadir7 commented on Packages/manifest.json
> +    "com.unity.toolchain.win-x86_64-linux-x86_64": "2.0.2",
Что за пакеты появились, для чего нужны?

2022-09-04 04:06 UTC, Zadir7 commented on ProjectSettings/ProjectSettings.asset
> +  m_BuildTargetPlatformIcons:
А тут что произошло и зачем?

2022-09-05 17:25 UTC, ivan1209-stack commented on Packages/manifest.json
> +    "com.unity.toolchain.win-x86_64-linux-x86_64": "2.0.2",
пакеты видимо добавились из-з того что я при установке выбрал все пункты

2022-09-05 17:41 UTC, ivan1209-stack commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            var currentDirection = View.transform.InverseTransformDirection(Vector3.up);
Потому что _targetDIrection в локальных координатах врага

2022-09-05 17:43 UTC, ivan1209-stack commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            if (!UnityHelper.Approximately(_targetDirection, currentDirection, 0.1f))
не понял, если не смотрим на цель не стреляем, это прописано в условии на 50 строке

2022-09-05 17:46 UTC, ivan1209-stack commented on ProjectSettings/ProjectSettings.asset
> +  m_BuildTargetPlatformIcons:
Честно не знаю, может потому что редактор в настройках указал

2022-09-08 06:21 UTC, Zadir7 commented on Packages/manifest.json
> +    "com.unity.toolchain.win-x86_64-linux-x86_64": "2.0.2",
Убирай лишние пакеты и project settings

2022-09-08 06:40 UTC, Zadir7 requested changes
Допиливаем, отвечаем

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyBehaviour.cs
> +            Config = Resources.Load<EnemyConfig>("Configs/Enemy/EnemyConfig").Behaviour;
Нетушки, это хреновая идея так делать
Если другие типы врагов появятся, как это решать будешь?
Ты тут должен только присвоить переданный BehaviourConfig, а не грузить его вручную

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            if (!UnityHelper.Approximately(_targetDirection, currentDirection, 0.1f))
Ну так условие (если не смотрим на цель), а действие - CommenceFiring
Я и спросил, если не смотрим на цель, стреляем?)

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            _shootingDistance = Config.ShootingDistance;
А не проще оставить здесь BehaviourConfig?
Вдруг тебе еще агро-радиус тут понадобится, чтобы враг "отстал" от игрока при выходе из радиуса?

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            var quarterMaxSpeed = _movementModel.MaxSpeed;
Теперь вопрос, почему переменная называется "четвертьМаксСкорости" а присваивается в нее макс скорость?
И скорости тебе теперь сравнивать не надо по сути, только жать тапку в пол (ускоряться всегда)

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            var currentDirection = View.transform.InverseTransformDirection(Vector3.up);
Я спросил почему InverseTransformDirection, потому что во всех остальных случаях используется TransformDirection,(не инверс), интересно чем обусловлено.

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyRoamingBehaviour.cs
> +            _flagPicker =  true;
Я в итоге так и не понял зачем нужен этот флаг
Тикай себе таймер и когда он <= 0 становится, ресетни его и вызови метод который тебе нужен.

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyRoamingBehaviour.cs
> +        private void TimeToUpdateMethod()
Был же TickDownTimer, не?

2022-09-08 06:40 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyRoamingBehaviour.cs
> +        private void ChangerState()
Тоже DetectPlayer.
Почему если в одном месте поменял то в другом такое же остается?

2022-09-08 06:40 UTC, Zadir7 commented on ProjectSettings/ProjectSettings.asset
> +  m_BuildTargetPlatformIcons:
Убирай лишние пакеты и project settings

2022-09-08 06:41 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +        private readonly EnemyView _enemyView;
Все еще осталось _enemyView, которое есть в базовом классе

2022-09-10 06:02 UTC, ivan1209-stack commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            _shootingDistance = Config.ShootingDistance;
когда не смотрит не стреляет

2022-09-10 06:03 UTC, ivan1209-stack commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyRoamingBehaviour.cs
> +        private void TimeToUpdateMethod()
нет вроде

2022-09-10 12:44 UTC, ivan1209-stack commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            if (!UnityHelper.Approximately(_targetDirection, currentDirection, 0.1f))
нет не стреляем

2022-09-10 12:57 UTC, ivan1209-stack commented on Packages/manifest.json
> +    "com.unity.toolchain.win-x86_64-linux-x86_64": "2.0.2",
в projectsettings убрать не могу, unity сам их докидывает

2022-09-11 10:42 UTC, Zadir7 requested changes
Хотел уже замержить и мелкие правки сам сделать, но ты залил сюда другую задачу зачем-то.

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            _shootingDistance = Config.ShootingDistance;
???

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Input/KeyboardInputView.cs
> +            Debug.Log(horizontalOffset);
Почему сюда залетели изменения из другой задачи? Другую задачу надо было делать в отдельной ветке. Убирай.

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyRoamingBehaviour.cs
> +        private void TimeToUpdateMethod()
Так переименуй, почему метод сущ-ным называется?

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyRoamingBehaviour.cs
> +            _timeToPickNewAngle = Config.TimeToPickNewAngle;
Так а не проще избавиться от лишних полей если ты конфиг уже передал сюда?

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyIdleBehaviour.cs
> +            _playerDetectionRadius = Config.PlayerDetectionRadius;
Так а не проще избавиться от лишних полей если ты конфиг уже передал сюда?

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +                case 1: { _inputController.Decelerate(); return; }
Так а зачем теперь тут сравнивать скорости если ты всегда будешь ускоряться?
Замени на _inputController.Accelerate(); и будет счастье

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            }
Так в итоге почему здесь условие "не смотрит на игрока" а действие выстрел?

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyCombatBehaviour.cs
> +            _shootingDistance = Config.ShootingDistance;
Убираем лишние поля, ты же конфиг передал сюда уже.

2022-09-11 10:42 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/Behaviour/EnemyBehaviourController.cs
> +        private readonly EnemyConfig _enemyConfig;
Так а если ты в Behaviour'ы передал EnemyBehaviourConfig, зачем тебе здесь то целый конфиг хранить? Храни тут тоже EnemyBehaviourConfig

2022-09-11 10:42 UTC, Zadir7 commented on .idea/.idea.SpaceRogue/.idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Убирай этот файл из репо, там в гитигноре добавится .idea потом

2022-10-08 06:35 UTC, Zadir7 approved these changes
Пофиксил gitignore, manifest и package-lock.
Пойдет.

2022-10-08 06:37 UTC, merged