Mouse rotation
Zadir7/SpaceRogue pull request #39
Opened 2022-10-30 16:37 UTC by NewdayTurnaway

2022-11-07 15:26 UTC, Zadir7 requested changes
На доработку

2022-11-07 15:26 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +            _view.transform.rotation = Quaternion.AngleAxis(rotationAngle, Vector3.back);
У тебя здесь получается что у тебя поворот ни разу не зависит от прописанной модели передвижения, у меня игрок в результате крутится как упоротый. Логика практически правильная, но движение должно осуществляться через метод выше.

2022-11-07 15:26 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +        private void HandleHorizontalMouseInput(Vector3 newMousePositionInput)
Плюсом к предыдущему комменту, получается что поворот зависит сразу и от клавиш, и от мышки, по идее надо бы что-то одно тогда оставить

2022-11-12 06:46 UTC, Zadir7 requested changes

2022-11-12 06:46 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Input/BaseInputView.cs
> +            _mousePositionInput = mousePositionInput;
А зачем понадобилось переименовывать?)

2022-11-12 06:46 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementConfig.cs
> +        [SerializeField] public float turnRateMultiplier = 0.1f;
Почему это здесь?
Множитель поворота у нас на инпут контроллере, почему про это должна знать модель передвижения?

2022-11-12 08:14 UTC, NewdayTurnaway commented on Assets/Scripts/Gameplay/Input/BaseInputView.cs
> +            _mousePositionInput = mousePositionInput;
Чтобы четко показать, что передается позиция мыши(Vector3), а не значение виртуальной оси(float).

2022-11-12 08:15 UTC, NewdayTurnaway commented on Assets/Scripts/Gameplay/Movement/MovementConfig.cs
> +        [SerializeField] public float turnRateMultiplier = 0.1f;
Раньше у нас передавалось значение по горизонтальной оси? скорректированное множителем, и уже это значение использовалось при повороте. 
Сейчас передается положение мыши, его корректировать множителем бессмысленно. 
Вывел множитель поворота в модель, чтобы можно было легко это значение получить и не пробрасывать значение из инпут контроллера.
В целом я могу пробросить это значение через z координату положения мыши, но это уже какой-то костыль, как по мне.

2022-11-23 16:02 UTC, Zadir7 requested changes
Маленький фикс нужен

2022-11-23 16:02 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Modules/EngineModuleConfig.cs
> +        [SerializeField] public float turnRateMultiplier = 0.1f;
Ну если в плане поворота мышки он не нужен, тогда убери его совсем, будем чистыми значениями настраивать)

2022-11-24 07:41 UTC, closed without merging