Fast asteroids ready
Zadir7/SpaceRogue pull request #69
Opened 2023-02-08 19:45 UTC by Ramio7

https://gamelineentertainment.aspro.cloud/_module/task/view/task/44 is ready to test, please take a look

2023-02-21 15:13 UTC, Zadir7 requested changes
Есть много вопросов, нужны доработки

2023-02-21 15:13 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidBehaviour.cs
> +        protected virtual void OnDispose() { }
У тебя по факту всего 2 варианта поведения астероида как я понял: движение по прямой и статика, нафига пустой класс-прародитель?

2023-02-21 15:13 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +        Vector3 _vector;
Модифиакторы доступа потерялись

2023-02-21 15:13 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidClouds/AsteroidCloudConfig.cs
> +        [NonSerialized] public int MaxAsteroidsInCloud;
Опечатка и нужно пояснение

2023-02-21 15:13 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField] public string Id { get; private set; } = Guid.NewGuid().ToString();
Зачем?

2023-02-21 15:13 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidsSpawnConfig.cs
> +        [field: SerializeField] public List<AsteroidConfig> AsteroidConfigs;
Публичные поля, ничем не ограниченные

2023-02-21 17:30 UTC, Ramio7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField] public string Id { get; private set; } = Guid.NewGuid().ToString();
Досталось в наследство. Не стал менять т.к. думал, что необходимо в других частях проекта. Если не нужно - убираю

2023-02-21 17:44 UTC, Ramio7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidClouds/AsteroidCloudConfig.cs
> +        [NonSerialized] public int MaxAsteroidsInCloud;
На этом участке опечатки нет. Поля действительно не сериализуемые. Это нужно для того, чтобы при создании конфига астероидных полей разных типов не задваивались поля, на которые в этих конфигах накладываются ограничения.

2023-02-21 17:48 UTC, Ramio7 commented on Assets/Resources/Prefabs/Gameplay/PlanetIcons/Earth.png.meta
>  fileFormatVersion: 2
Аналогично с комментарием ниже. Сюда не лез и даже не знал, что они куда-либо переезжали. Переношу в папку спрайтов

2023-02-21 17:50 UTC, Ramio7 commented on Assets/Resources/Prefabs/Gameplay/Asteroids/AsteriodClouds.prefab
> +%YAML 1.1
В префабы не лазил. Брал то, что есть. Даже не представляю в чём опечатка. Скажите, где именно, пожалуйста. Буду отлавливать в будущем

2023-02-21 17:51 UTC, Ramio7 commented on Assets/Resources/Configs/Enemy/EnemySpawnConfig.asset
>    <EnemyGroupsSpawnPoints>k__BackingField:
Сделаю. Возможно действительно разница версий

2023-02-21 17:51 UTC, Ramio7 commented on Assets/Resources/Prefabs/Gameplay/Asteroids/AsteriodClouds 1.prefab
> +%YAML 1.1
В префабы не лез. Сейчас исправлю название

2023-02-21 17:55 UTC, Ramio7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidsSpawnConfig.cs
> +        [field: SerializeField] public List<AsteroidConfig> AsteroidConfigs;
Исправил, сейчас подгружу в гит изменения

2023-02-21 18:00 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        public int Id;
Так и должно быть. Id присвается основным контроллеров во время спавна астероида. Планировалось использование в обзёрвере для столкновений астероидов. На данный момент оставил на будущее

2023-02-21 18:01 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        public Action<AsteroidController> OnDestroy;
Должно быть. Используется при уничтожении астероидов для вызова Dispose на конкретном контроллере. Нужно для своевременной очистки памяти от неиспользуемых данных

2023-02-21 18:03 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        private readonly AsteroidView _view;
Сделано, скоро подгружу изменения

2023-02-21 18:15 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        }
Предлагаете выделить дочерние классы? В контроллере поведения тоже 3 конструктора и один общий для всех метод создания поведения. Это можно также решить наследованием.

2023-02-21 18:19 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +            healthController.SubscribeToOnDestroy(OnDispose);
Когда смотрел HealthController - запутался где он диспоузится и решил перестраховаться и прописать дополнительно у себя диспоуз. К тому же в EnemyController используется точно такой же приём и я решил, что не совершаю ошибку такой перестраховкой.

2023-02-21 18:20 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +        #endregion
Неудобно читать код с регионами? Уберу тогда. Мне показалось хорошей идеей отделить основные используемые методы и вспомогательные.

2023-02-21 18:22 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +        {
Хм... Тут использовал инструмент VS по автовыравниванию... Перепроверю табуляции.

2023-02-21 18:25 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +            return spawnTries;
Я выполняю проверку на количество попыток в основном методе. Если количество превышено, то в контроллер возвращается null.
Изначально не выделял этот код в отдельный метод, но подумал, что для чтения будет удобнее, да и повторяется он в разных методах.

2023-02-21 18:29 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +                var currentConfig = Random.Range(0, config.CloudAsteroidsConfigs.Count);
Там немного другая специфика. Тот метод для одиночных астероидов, а в этом создаётся облако.

2023-02-21 18:29 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +                                                                     config.AsteroidCloudSize);
Понял, проверяю

2023-02-21 18:30 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +                    if (currentAsteroid != null) asteroidControllersOutput.Add(currentAsteroid);
Исправил, скоро залью в гит

2023-02-21 18:31 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +        private void AsteroidInCloudMoveTypeSwitch(AsteroidCloudConfig config)
Внёс правки, скоро подгружу

2023-02-21 18:32 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +                        AsteroidMoveTypeSet(config, AsteroidMoveType.Static);
Спасибо за совет. Поправил

2023-02-21 18:34 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +            var spawnPosition = (Vector2)spawnPoint + Random.insideUnitCircle * spawnRadius;
В проекте облако задаётся прямоугольником. Получается, что доступный для спавна астероида радиус в два раза меньше большей из его сторон

2023-02-21 18:41 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidType.cs
> +namespace Asteroid
Сделано

2023-02-21 18:42 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidView.cs
> +
Убрал :)

2023-02-21 18:44 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +                _timer.Start();
Не углядел. Поправил

2023-02-21 18:47 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +        private bool _appIsQuiting = false;
Использую при деспавне отдельных астероидов. В случае если деспавн происходит из-за завершения приложения, то новые объекты не создаются. Это есть в методе DeleteAsteroidController. Во время тестирования я ловил ошибки формата - программа не может выполнить автоматическую очистку памяти т.к. некоторые экземпляры объектов созданы после завершения работы приложения. Придумал такое решение.

2023-02-21 18:48 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +
Поправил

2023-02-21 18:50 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +            int maxTries = 5;
Они используются только в одном методе и не выходят за его пределы. Не стал выделять константы для них, чтобы сразу удалялись из памяти.

2023-02-22 10:40 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidClouds/AsteroidCloudConfig.cs
> +        [NonSerialized] public int MaxAsteroidsInCloud;
AsteroidConfigType._Astreoid_CloudConfig - таки есть)

2023-02-22 10:43 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidClouds/BigAsteroidCloudConfig.cs
> +        [field: SerializeField, Min(25)] public new int MaxAsteroidsInCloud { get; private set; } = 25;
Не смотри в ДД по поводу значений. Выставил про умолчанию те, что написаны - хорошо. Но ограничивать их применение надо исходя из здравого смысла. ГД захочет сделать не 12 а 8 астероидов - лезем в код?
Тут по хорошему должно быть минимальное ограничение - 2 (ну или 1) (2 чтобы считалось "группой" по логике), и максимальное - 99

2023-02-22 10:44 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField] public string Id { get; private set; } = Guid.NewGuid().ToString();
Identity нужно для множественных объектов, типа предметов инвентаря.
Посмотри есть ли такая штука у врагов, и если нет - однозначно убирай.

2023-02-22 10:55 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/Legacy/AsteroidCloudSpawn.cs
> +using Asteroid;
Я еще не заметил вчера, папку Legacy - под снос. Нефиг держать мертвый код.

2023-02-22 10:55 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidClouds/AsteroidCloudConfig.cs
> +    [Serializable]
Эта штука должна быть ScriptableObject'ом, а не просто Serializable
Тут и передача по интерфейсу не особо нужна, должен быть WeightConfig'и там где определяется спавн, и соответственно шанс спавна не нужен.

2023-03-01 19:40 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +            int maxTries = 5;
Вывел константу отдельно

2023-03-01 19:52 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +            var spawnPointClaimed = false;
Поправил

2023-03-01 19:52 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidsController.cs
> +                cancellationToken = Vector3.one;
После правок по предыдущему пункту - не актуально

2023-03-01 20:00 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidBehaviourConfig.cs
> +    public class AsteroidBehaviourConfig
Этот класс встроен в конфиг астероида. Его не нужно отдельно создавать

2023-03-01 20:13 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidLinearMotionBehavior.cs
> +            _rigidbody.AddForce(speed * Time.deltaTime * direction, ForceMode2D.Force);
Поправил во всех типах поведения

2023-03-01 20:13 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidLinearMotionBehavior.cs
> +            _rigidbody = _view.GetComponentInParent<Rigidbody2D>();
Поправил

2023-03-01 20:14 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidBehaviour.cs
> +            EntryPoint.UnsubscribeFromUpdate(OnUpdate);
Делал как в EnemyBehaviour. Думаю, что в полном паттерне действительно нет нужды. Исправил

2023-03-01 20:25 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidBehaviour.cs
> +        protected virtual void OnDispose() { }
Оставляю этот класс для возможности расширения до более сложных паттернов вроде движения по орбите

2023-03-01 20:28 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +        Vector3 _vector;
Поправил

2023-03-01 20:30 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +        private float _rotationSpeed = 0.1f;
Сделал обычную переменную. Константа не оставляет возможностей для модификации

2023-03-01 20:34 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +            _vector = (random.Next(2) == 1) ? new Vector3(0, 0, -_rotationSpeed) : new Vector3(0, 0, _rotationSpeed);
Досталось от предшественника. Как я понял - это выбор направления вращения

2023-03-01 20:34 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Legacy/AsteroidDestructionView.cs
> +        private float _currentAsteroidSpawnTime = 0.7f;
Удалил файл т.к. легаси

2023-03-01 20:34 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Legacy/AsteroidExplosionController.cs
> +        public AsteroidDestructionView AsteroidDestructionView { get; set; }
Легаси. Удалил

2023-03-01 20:35 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Legacy/AsteroidExplosionController.cs
> +        private GameObject _explosion;
Легаси. Удалил

2023-03-01 20:35 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Legacy/AsteroidExplosionController.cs
> +        public AsteroidExplosionController()
Легаси. Удалил

2023-03-01 20:36 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Enemy/EnemyFactory.cs
> +            _enemyPool.transform.SetPositionAndRotation(new Vector3(9999, 9999), Quaternion.identity);
Для астероидов так же сделал. Пустой объект на трансформ которого подвешиваем наших врагов и прочие кучкующиеся объекты.

2023-03-01 20:38 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Player/PlayerView.cs
> +using Gameplay.Damage;
Конечно убираем. Сделано

2023-03-01 20:40 UTC, Ramio7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidClouds/AsteroidCloudConfig.cs
> +        [NonSerialized] public int MaxAsteroidsInCloud;
Поправил

2023-03-02 03:00 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        public int Id;
Не должно быть. Как максимум это может быть публичное свойство с ограничением доступа private на сеттер.

2023-03-02 03:02 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        public Action<AsteroidController> OnDestroy;
Таки где оно тогда?) где ключевое слово event, где инициализация события по аналогии с остальным кодом?

2023-03-02 03:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +                var currentConfig = Random.Range(0, config.CloudAsteroidsConfigs.Count);
Какая разница какая специфика если есть метод выбора одной сущности из списка?)

2023-03-02 03:13 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +        private float _rotationSpeed = 0.1f;
А почему тут должна быть возможность модицикации?)

2023-03-02 03:14 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +            _vector = (random.Next(2) == 1) ? new Vector3(0, 0, -_rotationSpeed) : new Vector3(0, 0, _rotationSpeed);
Перепиши поадекватнее тогда, очень сложно сразу понять что тут происходит.

2023-03-02 03:16 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Enemy/EnemyFactory.cs
> +            _enemyPool.transform.SetPositionAndRotation(new Vector3(9999, 9999), Quaternion.identity);
Как бы делать new GameObject это вроде плохая практика, почему не заюзал Instantiate? Там сразу можно и точку спавна и поворот задать.

2023-03-02 04:16 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        public int Id;
Понял. Поправлю и подгружу

2023-03-02 04:51 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidController.cs
> +        public Action<AsteroidController> OnDestroy;
Модификатор event добавил
Используется в следующих методах класса AsteroidsController. Думаю, надо его переименовать, но пока не могу определиться как лучше. Хоть пулом обзывай...
private void RegisterAsteroidController(List<AsteroidController> asteroidCloudAsteroids)
        {
            for (int j = 0; j < asteroidCloudAsteroids.Count; j++)
            {
                _asteroidsControllers.Add(asteroidCloudAsteroids[j]);
                asteroidCloudAsteroids[j].Id = _asteroidsControllers.Count - 1;
                asteroidCloudAsteroids[j].OnDestroy += DeleteAsteroidController;
            }
        }

private void RegisterAsteroidController(AsteroidController spawnedAsteroid)
        {
            _asteroidsControllers.Add(spawnedAsteroid);
            spawnedAsteroid.Id = _asteroidsControllers.Count - 1;
            spawnedAsteroid.OnDestroy += DeleteAsteroidController;
        }

2023-03-02 05:00 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/AsteroidFactory.cs
> +                var currentConfig = Random.Range(0, config.CloudAsteroidsConfigs.Count);
Сорян, проверил, нет такого

2023-03-02 05:03 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +        private float _rotationSpeed = 0.1f;
_rotationSpeed присваивается в конструкторе через рандомайзер. Если делать константу, то не сработает и все астероиды будут вращаться одинаково

2023-03-02 05:13 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroid/Behaviour/AsteroidStaticBehavior.cs
> +        private float _rotationSpeed = 0.1f;
Ну так если оно присваивается в конструкторе, сделай его readonly и убери значение по умолчанию

2023-03-02 05:30 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Enemy/EnemyFactory.cs
> +            _enemyPool.transform.SetPositionAndRotation(new Vector3(9999, 9999), Quaternion.identity);
Для Instantiate нужна ссылка на объект. То есть я так же должен буду создать пустой ГО внутри кода и потом передать его в метод. Думаю, что это ещё хуже.

2023-03-10 15:13 UTC, Zadir7 commented
Closed due to change of task

2023-03-10 15:13 UTC, closed without merging