Leaps and cooldown
Zadir7/SpaceRogue pull request #72
Opened 2023-02-14 18:46 UTC by Mamay-ka

2023-02-14 18:47 UTC, Mamay-ka commented
Leaps and cooldown

2023-02-16 13:39 UTC, Zadir7 requested changes
В целом норм но есть вопросы.

2023-02-16 13:39 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementConfig.cs
> +        [Header("Leap")]
Есть предложение переименовать Leap в Dash. Все-таки это именно рывок, а не прыжок в классическом понимании.

2023-02-16 13:39 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
>          public MovementModel(MovementConfig config)
1. Между блоками кода нужно оставлять пробелы.
2. Публичные поля

2023-02-16 13:39 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
> +            LeapLengthMultiplier = 100000f;
Что это за множитель и почему он принимает именно такое значение?

2023-02-16 13:39 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +                _cooldownLeapTimer.Start();
Два одинаковых блока кода которые отличаются только знаком.

2023-02-16 13:39 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementModel.cs
> +        public float LeapLengthMultiplier;
Зачем эта штука появляется в 3х местах а используется только в одном?

2023-02-16 13:39 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +                _rigidbody.AddForce(sideDirection.normalized * _model.LeapLength * _model.LeapLengthMultiplier, ForceMode2D.Force);
Получается, если я нажму рывок в сторону при продолжающемся полете, будет очень короткий рывочек в сторону а потом ничего не произойдет?

2023-02-16 17:24 UTC, Mamay-ka commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
> +            LeapLengthMultiplier = 100000f;
LeapLengthMultiplier я ввел, чтобы в инспекторе не вводить большие числа. Вместо того, чтобы писать 25 000, можно ввести 2,5. Только для этого.

2023-02-16 17:25 UTC, Mamay-ka commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +                _rigidbody.AddForce(sideDirection.normalized * _model.LeapLength * _model.LeapLengthMultiplier, ForceMode2D.Force);
При продолжающемся полете должен произойти рывок в сторону(нужно установить длину рывка в playerConfig), а потом продолжается полет вперед.

2023-02-19 03:17 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
> +            LeapLengthMultiplier = 100000f;
Почему его тогда в константу не вынести?
И все же, почему такой большой множитель? Просто для стороннего наблюдателя выглядит как костыль

2023-03-01 06:07 UTC, Zadir7 requested changes
Все еще есть некоторые вопросы

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
> +
1. Публичные поля
2. Отбитые пустой строкой хотя по сути они к одному блоку относятся
3. Зачем они нужны в модели если они тут не используются?

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
> +
Лишние пустые строки

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementModel.cs
> +
Лишние пробелы

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +
Лишний пробел

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementController.cs
> +                Dash(dashDirectionRight);
Все еще 2 блока которые отличаются только знаком.
Форматирование поехало (лишние пробелы там где они не нужны)

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Movement/MovementConfig.cs
> +        [SerializeField] public float DashCooldown = 0.1f;
Значения по умолчанию по минимальным - почему?

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementModel.cs
> +
Лишние пустые строки, которые при этом в неизмененном файле

2023-03-01 06:07 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Player/Movement/PlayerMovementModel.cs
> +
Лишние пустые строки, которые при этом в неизмененном файле

2023-03-09 16:00 UTC, Zadir7 commented
Closed due to change of task

2023-03-09 16:00 UTC, closed without merging