BlackHole_and_magnetar
Zadir7/SpaceRogue pull request #76
Opened 2023-02-21 10:30 UTC by Bharmaglot

BlackHole_and_magnetar Bolbat

2023-02-22 10:37 UTC, Zadir7 requested changes
Есть серьезные вопросы.
1. Нейминг страдает
2. Консистентность (однообразие кода) сильно страдает
3. Основной выбранный подход некорректен и я об этом уже говорил
4. По пункту 3 считаю что реализовать с нуля проще чем переписывать текущий код, но решение за тобой.

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityController.cs
> +            GravityView.transform.parent = BlackHoleParent;
То же самое, зачем это в контроллере?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityController.cs
> +            PointEffector.forceMagnitude = -gravityConfig.ForceGravity;
А что со знаком?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityController.cs
> +        public PointEffector2D PointEffector;
Консистентность пострадала

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityView.cs
> +    [RequireComponent(typeof(CircleCollider2D), typeof(PointEffector2D))]
Так работает?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/Star/StarView.cs
> +    public class StarView : MonoBehaviour, IDamagingView
Вернуть

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/GravityConfig.cs
> +        [field: SerializeField, Range(1f, 5f)] public float RadiusGravity { get; private set; }
Нейминг - GravityForce, GravityRadius
Почему одно ограничено, а второе нет?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/GravityOfTypeConfig.cs
> +    public class GravityOfTypeConfig : ScriptableObject
Конфиг гравитации типа? Чего?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/GravityOfTypeConfig.cs
> +        [field: SerializeField] public GravityConfig MagnetarConfig { get; set; }
Модификаторы доступа на сеттерах потерялись

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/PlanetSystemOfTypeConfig.cs
> +        [field: SerializeField] public PlanetarySystemConfig RedGiantConfig { get; set; }
Нейминг пострадал опять
Лишние пробелы
Модификаторы доступа на сеттерах

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/PlanetarySystemConfig.cs
> +
Лишние пробелы

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/RepeatableDamageConfig.cs
> +        [field: SerializeField] public DamageZoneView Prefab { get; private set; }
Зачем тут нужен префаб?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/RepeatableDamageConfig.cs
> +        [field: SerializeField, Min(1.1f)] public float DamageCooldown { get; private set; }
Почему DamageValue не ограничен снизу, а DamageCooldown ограничен таким странным числом?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/RepeatableDamageOfTypeConfig.cs
> +        [field: SerializeField] public RepeatableDamageConfig MagnetarConfig { get; set; }
Нейминг
Модификторы доступа на сеттерах
А если я в блекхол положу конфиг магнетара, что будет?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/StarConfig.cs
> +    public class StarConfig : ScriptableObject
Вернуть

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Space/StarConfig.cs
> +        [field: SerializeField] internal SpaceObjectType Type;
Почему internal и почему это поле.

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/SpaceController.cs
> +                }
Нейминг и консистентность пострадали

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/Generator/SpaceGenerator.cs
> +            var radius = (maxStarSize)
Нормально, то есть у нас для планет орбита это радиус звезды?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/Factories/SpaceObjectFactory.cs
> +                    damageZone = _damageZoneAreaFactory.CreateDamageZone(starsParent);
Я тебе сразу говорил что это некорректный подход

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/Factories/SpaceObjectFactory.cs
> +                    Debug.Log("��������� ���-�� ����������");
Что с кодировкой?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/Factories/SpaceObjectFactory.cs
> +                    _damageZoneAreaFactory = new DamageZoneAreaFactory(starSpawnPosition, starSize, _repeatebleDamageOfTypeConfig.BlackHoleConfig);
Нафига каждый раз переинициализировать фабрики?

2023-02-22 10:37 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/Factories/GravityAreaFactory.cs
> +            _centerObjectSize = starSize;
Почему слева объект а справа звезда?

2023-02-22 11:17 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/Factories/SpaceObjectFactory.cs
> +                    _damageZoneAreaFactory = new DamageZoneAreaFactory(starSpawnPosition, starSize, _repeatebleDamageOfTypeConfig.BlackHoleConfig);
Принято, исправил.

2023-02-22 11:17 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/Factories/SpaceObjectFactory.cs
> +                    Debug.Log("��������� ���-�� ����������");
Принято, исправил.

2023-02-22 11:41 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/SpaceController.cs
> +                }
Нейминг поправил

2023-02-22 11:43 UTC, Bharmaglot commented on Assets/Scripts/Scriptables/Space/StarConfig.cs
> +    public class StarConfig : ScriptableObject
Исправил, вернул (убирал, пока пробовал делать наследников от класса)

2023-02-22 11:45 UTC, Bharmaglot commented on Assets/Scripts/Scriptables/Space/StarConfig.cs
> +        [field: SerializeField] internal SpaceObjectType Type;
Исправил на public, для доступа в фабрике. Поле для указания типа объекта.

2023-02-22 11:48 UTC, Bharmaglot commented on Assets/Scripts/Scriptables/Space/RepeatableDamageConfig.cs
> +        [field: SerializeField] public DamageZoneView Prefab { get; private set; }
В префабе лежит коллайдер, с которым происходит контакт +изображение под визуализацию зоны урона (ее как раз можно удалить, но, кмк, при настройке ее можно видеть).

2023-02-22 11:55 UTC, Bharmaglot commented on Assets/Scripts/Scriptables/Space/RepeatableDamageConfig.cs
> +        [field: SerializeField, Min(1.1f)] public float DamageCooldown { get; private set; }
DamageCooldown ограничен странным числом, так как обновление таймера на 1f в самом уроне. Хотя это не обязательно, если изменить таймер получения урона. Изменю. Но ограничу 0, так как отрицательного кулдауна не должно быть.

2023-02-22 11:59 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityView.cs
> +    [RequireComponent(typeof(CircleCollider2D), typeof(PointEffector2D))]
Да, а не должно?

2023-02-22 12:00 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/Star/StarView.cs
> +    public class StarView : MonoBehaviour, IDamagingView
Вернул.

2023-02-22 12:01 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityController.cs
> +        public PointEffector2D PointEffector;
Тут в дискорде попрожу уточнить.

2023-02-22 12:03 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityController.cs
> +            PointEffector.forceMagnitude = -gravityConfig.ForceGravity;
У поинт-эффектора пложительное значение - отталкивает объект, а отрицательное - притягивает. Так как в игре речь про гравитацию и актуально притяжение, я просто поставил отрицательное значение, и в конфиге оно указывается положительным.

2023-02-22 12:05 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Damage/IRepeatableDamageView.cs
> +        public float CooldownDamage { get; set; }
Урон идет от старой модели, а эта модель только говорит о его повторяемости. переменную переименую.

2023-02-22 12:16 UTC, Bharmaglot commented on Assets/Scripts/Scriptables/Space/RepeatableDamageOfTypeConfig.cs
> +        [field: SerializeField] public RepeatableDamageConfig MagnetarConfig { get; set; }
Будет использоваться конфиг магнетара. Я сейчас попробую понять как, но есть версия, что это должен быть тоже лист конфигов, выбор которых отталкивается от типа объекта, но и сами конфиги должны свой тип получать.

2023-02-22 12:17 UTC, Bharmaglot commented on Assets/Scripts/Scriptables/Space/PlanetarySystemConfig.cs
> +
Убрал.

2023-02-22 12:19 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Damage/IRepeatableDamageView.cs
> +        public float CooldownDamage { get; set; }
А почему интерфейсы должны зависеть друг от друга?
Если ты хочешь такую реализацию, тогда у тебя RepeatableDV должен наследовать DV

2023-02-22 12:21 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/Gravity/GravityView.cs
> +    [RequireComponent(typeof(CircleCollider2D), typeof(PointEffector2D))]
Я писал отдельные атрибуты для каждого компонента, не знал про такое

2023-02-22 19:23 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Space/SpaceObjectEffects/DamageZone/DamageZoneController.cs
> +            DamageZoneView.transform.parent = spaceObjectParent;
Ну, тут я честно делал по аналогии с готовым StarController, как было в изначальной версии, если речь про вью и трансформ.

2023-02-27 16:11 UTC, closed without merging

2023-02-27 16:11 UTC, Zadir7 commented
Closed due to change of task.