Single asteroid ready
Zadir7/SpaceRogue pull request #90
Opened 2023-03-24 21:02 UTC by Ramio7

Asteroids is spawning and moving
Damage and survival is added, but not working

2023-03-25 15:35 UTC, Zadir7 requested changes
Есть вопросы по некоторым решениям

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +            var asteroidOrbit = RandomPicker.PickRandomBetweenTwoValues(0, newAsteroidConfig.MaxAsteroidSpawnOrbit);
Орбита астероида?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +            while (spawnTries <= MaxSpawnTriesPerAsteroid);
6 раз сработает

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Installers/AsteroidsInstaller.cs
> +            Container.BindFactory<AsteroidMoveConfig, AsteroidView, Vector2, AsteroidMovement, AsteroidMovementFactory>().AsSingle();
Привести к такому же виду как в других фабриках - сгруппировать по типу, и вынести в более мелкие методы, с соблюдением код стайла

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/LevelProgress/LevelFactory.cs
> +        private readonly AsteroidObjectsFactory _asteroidsInSpaceFactory;
Почему у класса одно название а у поля другое?
Вообще AsteroidObjects - не лучшее название

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Pooling/AsteroidsPool.cs
> +
Sealed потерял, пустую строку не убрал)

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Services/Level.cs
> +        public int AsteroidsCreatedOnStart { get; private set; }
Зачем это тут?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Shooting/Weapons/NullGun.cs
> +            Debug.Log($"None-gun has fired, bullet position {bulletPosition}, direction {turretDirection.eulerAngles}!");
Почему и зачем?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +    [CreateAssetMenu(fileName = nameof(AsteroidConfig), menuName = "Configs/AsteroidObjects/" + nameof(AsteroidConfig))]
Configs/Asteroids подходит лучше

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField] public AsteroidSizeType AsteroidSizeType { get; private set; }
А зачем везде приписки Asteroid если это и так конфиг астероида?
В 14 и 16 строке то же самое

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField, Min(0)] public float MaxAsteroidSpawnOrbit { get; private set; }
Что такое орбита астероида?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField, Min(0)] public float AsteroidLifeTime { get; private set; }
Если тип float, то Min должно быть в формате float для явности - 0.0f.
Значения по умолчанию?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidMoveConfig.cs
> +    [Serializable]
Если этот класс будет нужен, переделать на ScriptableObject

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidMoveConfig.cs
> +        [field: SerializeField, Min(0)] public float StartingForce { get; private set; }
Мб StartingSpeed?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidSpawnConfig.cs
> +        [field: SerializeField] public int StartingAsteroidsInSpaceNumber { get; private set; }
Почему это тут а не в LevelPreset?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidSpawnConfig.cs
> +    [CreateAssetMenu(fileName = nameof(AsteroidSpawnConfig), menuName = "Configs/AsteroidObjects/" + nameof(AsteroidSpawnConfig))]
Configs/Asteroids

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Damage/DamageConfig.cs
> +public class DamageConfig
Что это и зачем?

2023-03-25 15:35 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidMovement/AsteroidMovement.cs
> +        public AsteroidMovement(AsteroidView view, AsteroidMoveConfig config, Vector2 basePoint)
Пока не очень понятен смысл абстракции

2023-03-27 16:17 UTC, Ramio7 commented on Assets/Resources/Prefabs/Gameplay/Asteroids/Unused.meta
Это заготовки на префабы. К концу работы над астероидами она исчезнет

2023-03-27 16:21 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidView.cs
> +        [field: SerializeField] public Sprite Sprite { get; private set; }
Заранее закидываю их во вьюху через инспектор для экономии ресурсов. Сериализация для того, чтобы свойства в инспекторе отражались. Свойства применил, чтобы ограничить изменения данных извне.

2023-03-27 16:23 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidMovement/AsteroidMovement.cs
> +        private void SetAsteroidRotation() => View.gameObject.transform.Rotate(Vector3.forward, Config.RotationSpeed);
Для эффекта погружения. Мол у нас не просто картинки летают, а что-то похожее на настоящие каменюки

2023-03-27 16:28 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +            var asteroidRadius = newAsteroidConfig.AsteroidPrefab.Collider.radius;
Можно промежуточно добавить префаб, но я посчитал, что это лишнее.

2023-03-27 16:28 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +            var asteroidOrbit = RandomPicker.PickRandomBetweenTwoValues(0, newAsteroidConfig.MaxAsteroidSpawnOrbit);
Орбита его движения. Нейминг доработаю

2023-03-27 16:30 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Services/Level.cs
> +        public int AsteroidsCreatedOnStart { get; private set; }
По нему указывается сколько астероидов спавнить на старте. Используется напрямую в AsteroidObjects.

2023-03-27 16:31 UTC, Ramio7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField, Min(0)] public float MaxAsteroidSpawnOrbit { get; private set; }
Орбита в пределах которой спавнится астероид. Не стал менять работающие общие методы по спавну космических объектов

2023-03-27 16:34 UTC, Ramio7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidMoveConfig.cs
> +        [field: SerializeField, Min(0)] public float StartingForce { get; private set; }
Тут нет прямой корреляции с модулем скорости. Считаю, что называть это свойство скоростью некорректно - введёт в заблуждение GD.

2023-03-27 18:35 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +        public List<Asteroid> Asteroids { get; private set; } = new();
Сделал по примеру с врагами. В конструктор уровня передаётся количество созданных объектов

2023-03-27 18:53 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidMovement/AsteroidMovement.cs
> +        public AsteroidMovement(AsteroidView view, AsteroidMoveConfig config, Vector2 basePoint)
Когда запроектирую новые типы движения, то эта абстракция будет как раз к месту.  Нацеленное в игрока движение будет переопределять метод StartMovement для запуска астероида в сторону игрока, ускользающее движение будет направлять астероид в противоположную базовой точке сторону. можно так же задать полёт по орбите, только тогда движение будет постоянно корректироваться по отношению к центру масс.

2023-03-28 03:10 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +            while (Asteroids.Count < asteroidsOnStartCount || tryCount < MaxTriesToCreateStartAsteroids);
Я вижу смысл. Явное лучше неявного, а когда ты чего-то спавнишь в конструкторе, это:
1. Неявно.
2. Если тебе понадобится вынести интерфейс и сделать 2й вариант спавна, понадобится много рефакторить.

2023-03-28 03:11 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +            for (int i = 0; i < Asteroids.Count; i++) Asteroids[i].Dispose();
foreach
1. Чище
2. Быстрее
3. Про мусор не слышал

2023-03-28 03:14 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidMoveConfig.cs
> +        [field: SerializeField, Min(0)] public float StartingForce { get; private set; }
А StartingForce сразу вызывает вопрос, что за сила.
Так как у нас нет гравитации, считаю что назвать это скоростью вполне корректно

2023-03-28 03:36 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidMovement/AsteroidMovement.cs
> +        public AsteroidMovement(AsteroidView view, AsteroidMoveConfig config, Vector2 basePoint)
Прикол в том что по сути у тебя все движение определяется только направлением стартового вектора, поэтому я считаю эту абстракцию излишней.
А в движении по орбите одним только методом Start не обойдешься.

2023-03-28 03:40 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidConfig.cs
> +        [field: SerializeField, Min(0)] public float MaxAsteroidSpawnOrbit { get; private set; }
Все еще непонятно. Если подразумевается радиус спавна, так и обозначь что это радиус, а не орбита.

2023-03-28 03:41 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/Asteroid.cs
> +        }
Сделай явную подписку/отписку

2023-03-28 03:48 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidView.cs
> +        [field: SerializeField] public Sprite Sprite { get; private set; }
По-моему ты на этом не экономишь, а наоборот жрешь ресурсы, потому что у тебя вьюха вынуждена всегда знать про компоненты которые в ней даже не используются.
Оставь RequireComponent чтобы те кому нужны эти штуки могли получить их через GetComponent, и эти свойства стоит убрать.

2023-03-28 03:50 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidView.cs
> +            TakeDamage(DamageModel);
Не понял, почему астероид при столкновении получает урон от собственной модели?

2023-03-28 03:50 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidViewFactory.cs
> +            _diContainer = container;
Одно переименовал, второе нет

2023-03-28 03:53 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidView.cs
> +        public void InitDamageModel(DamageModel damageModel) => DamageModel = damageModel;
1. Ну так если здесь понадобится еще что-то инициализировать, ты в любом случае будешь инициализировать полностью вьюху.
2. Неконсистентно с остальным кодом получается.

2023-03-28 03:55 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/Asteroid.cs
> +            _view = asteroidView;
1. _view теперь можно сделать readonly
2. Почему ты в одном месте переименовал а в другом нет?

2023-03-28 04:02 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidMovement/AsteroidMovement.cs
> +        private void SetAsteroidRotation() => View.gameObject.transform.Rotate(Vector3.forward, Config.RotationSpeed);
Пока не вижу смысла в этом, мне кажется это бессмысленный расход ресурсов.

2023-03-28 04:02 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidObjects.cs
> +        public List<Asteroid> Asteroids { get; private set; } = new();
А зачем? В противниках это нужно чтобы считать количество убитых.

2023-03-28 04:03 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidView.cs
> +            TakeDamage(DamageModel);
Пока у меня не было других идей. Прописывать метод Fatal Damage, значит лезть в код, который сейчас редактируется не мной, что вызовет потом конфликт при мерже. Это, по сути, заплатка до того момента, когда в модели выживания появится метод, позволяющий уничтожить объект моментально.
В этой строчке я хотел отразить, что астероид должен разлетаться на куски от любого столкновения

2023-03-28 05:36 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Asteroid/AsteroidView.cs
> +            TakeDamage(DamageModel);
У планет вообще-то есть похожий метод, где они при столкновении разрушаются
А сейчас получается что при стрельбе по астероиду ему будет проходить урон пули + урон самого астероида, что некорректно
Если ты не хочешь лезть в код, но знаешь что нужно что-то сделать, оставь тудуху (//TODO make asteroid destroy on collision)

2023-03-28 05:46 UTC, Zadir7 requested changes
Все еще остались вопросы

2023-03-28 05:46 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Installers/AsteroidsInstaller.cs
> +        }
1. Методы в классе надо располагать в том же порядке как при вызове (чтобы не путаться, у тебя методы в обратном порядке сейчас)
2. Каждый Fluent метод надо писать с новой строки

2023-03-28 05:46 UTC, Zadir7 commented on Assets/Scripts/Scriptables/Asteroid/AsteroidSpawnConfig.cs
> +        [field: SerializeField] public List<WeightConfig<AsteroidConfig>> AsteroidPrefabs { get; private set; }
Почему AsteroidPrefabs?

2023-03-29 04:26 UTC, Zadir7 approved these changes
LGTM, немного причесал код.

2023-03-29 04:34 UTC, merged