Fast asteroids are ready and working
Zadir7/SpaceRogue pull request #96
Opened 2023-04-03 19:56 UTC by Ramio7

2023-04-04 03:43 UTC, Zadir7 requested changes
Необходимо сменить подход к движению астероидов, думаю быстрее будет сделать заново
1. Передвижение астероидов выродилось непонятно во что, сохранение каких-то чисел ради того чтобы использовать их в единственном методе (решение - убрать этот класс и добавить в Asteroid метод StartMoving с необходимыми параметрами. ScatteringAngle можно сделать опциональным параметром со значением по умолчанию 0.0f)
2. Спаунер быстрых астероидов должен идти дочерним по отношению к AsteroidsInSpace или вообще отдельной сущностью. Класть все в один класс это не выход.

2023-04-04 03:43 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidsInSpace.cs
> +            _playerTargetedAsteroidDelay.Start();
Задержка должна начинаться после спавна по идее

2023-04-04 03:43 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Factories/AsteroidTargetedMovementFactory.cs
> +    public override AsteroidTargetedMovement Create(float startingSpeed, AsteroidView view, Vector2 targetPosition, float directionScattering)
directionScattering непонятное название

2023-04-04 03:43 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Movement/AsteroidTargetedMovement.cs
> +        var directionDeviation = Random.insideUnitCircle * _directionScattering;
Если это направление отклонения, то deviationDirection

2023-04-04 03:43 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Scriptables/AsteroidConfig.cs
> +        [field: SerializeField, Min(0.0f)] public float DirectionScattering { get; private set; } = 0.0f;
ScatteringDirection?
Вообще почему Direction если это float?
ScatteringAngle должен быть получается?

2023-04-04 03:43 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Scriptables/AsteroidSpawnConfig.cs
> +        [field: SerializeField] public AsteroidConfig FastAsteroid { get; private set; }
А почему здесь не `List<WeightConfig>` ?

2023-04-04 17:57 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidsInSpace.cs
> +            _playerTargetedAsteroidDelay.Start();
Задержка в любом случае должна заново начаться, не зависимо от того, заспавнился астероид или нет. Иначе цикл прервётся.

2023-04-04 18:01 UTC, Ramio7 commented on Assets/Scripts/Gameplay/Asteroids/Scriptables/AsteroidSpawnConfig.cs
> +        [field: SerializeField] public AsteroidConfig FastAsteroid { get; private set; }
Я сначала хотел засунуть его в общий список конфигов, но в итоге пришёл к выводу, что выделить его отдельно надо, чтобы не путался в переборе спавнящихся на старте астероидов. Лист не стал делать потому, что по описанию задачи и комментариям Александра из ГД будет использоваться только один вид префаба для этого астероида - мол, зачем усложнять?

2023-04-07 13:06 UTC, Zadir7 requested changes
Остались небольшие вопросы, плюс небольшой архитектурный вопрос:
Почему не вынести отдельный сервис, который будет из локатора по таймеру брать игрока и спавнить быстрые астероиды?

2023-04-07 13:06 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/AsteroidsInSpace.cs
> +        private void GetNewAsteroid(Asteroid newAsteroid) => _asteroids.Add(newAsteroid);
Ну тут было бы тогда неплохо еще сразу подписаться на смерть этого астероида и убирать его из списка?

2023-04-07 13:06 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Asteroids/Factories/AsteroidSpawnerFactory.cs
> +            return new(finder, _factory);
Тут по идее надо заюзать
`return base.Create(finder)`
И тогда конструктор и фабрика не понадобятся

2023-04-07 13:06 UTC, Zadir7 commented on Assets/Scripts/Gameplay/Installers/AsteroidsInstaller.cs
> +        }
А тут порядок не перепутан?

2023-04-13 04:03 UTC, Zadir7 commented
Closed due to developer leaving the project

2023-04-13 04:03 UTC, closed without merging